name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Ensure GitHub NuGet Source
      run: |
        dotnet nuget add source https://nuget.pkg.github.com/zio3/index.json \
          -n github \
          -u zio3 \
          -p ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: BuildPackage
      run: dotnet pack --configuration Release -o pkgDir -p:Version=1.0.0.${{ github.run_number }}

    - name: PushPackage
      run: dotnet nuget push "GaPackage/bin/Release/GaPackage.1.0.0.${{ github.run_number }}.nupkg" --source "github" -k ${{ secrets.GITHUB_TOKEN }}
      
